[application]
name = "Cadoku"

[bundle]
identifier = "de.juliankarrer"
publisher = "Julian Karrer"
copyright = "Copyright 2025 Julian Karrer"
category = "PuzzleGame"
short_description = "A cozy, cat-themed sudoku app"

icon = ["assets/icon.png"]
default_platform = "web"
out_dir = "docs"
asset_dir = "public"

[web.app]
title = "Cadoku"
base_path = "cadoku"

[web.watcher]
reload_html = true
watch_path = ["src", "public", "assets"]
index_on_404 = true

