[application]
name = "Cadoku"

[bundle]
identifier = "de.juliankarrer"
publisher = "Julian Karrer"
icon = ["assets/icon.png"]

# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "docs"

# resource (public) file folder
asset_dir = "public"

[web.app]
title = "Cadoku"
base_path = "cadoku"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public", "assets"]
